alias ll='ls -Alh'
alias ls='ls -G'
alias grep='grep --color=auto'

alias gs='git status -uno'
alias gca='git commit --amend --no-edit'
alias gau='git add -u'
alias gc='git checkout '
alias gb='git branch '
alias gpo='git push origin '
alias gd='git diff '
alias gdt='git difftool '
alias gl='git log --online -10 '
alias glg='git log -all --decorate --online --graph -10 '
alias gg='git grep '

